"""add links to posts

Revision ID: 04551612b6df
Revises: dc67ac9cde43
Create Date: 2026-07-07 19:30:01.388078

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04551612b6df'
down_revision: Union[str, None] = 'dc67ac9cde43'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('links', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'links')
    # ### end Alembic commands ###
